### ISSUE TITLE
about:sync

### ISSUE THREAD

**Issue by fmarier** [mhammond/aboutsync#19]
Given the name of the add-on it would be nice if `about:sync` was an alias for `chrome://aboutsync/content/index.html`

**Comment by kitcambridge** [comment]
It looks like we can add a [contract](http://searchfox.org/mozilla-central/rev/957458d8fa2328c2a760dbb30e7f1f1efa55b4d0/mobile/android/components/MobileComponents.manifest#1-19) for `@mozilla.org/network/protocol/about;1?what=sync`, and a [component](http://searchfox.org/mozilla-central/rev/957458d8fa2328c2a760dbb30e7f1f1efa55b4d0/mobile/android/components/AboutRedirector.js#90,99-128) that implements `nsIAboutModule`. Hopefully, that's all we need?

**Comment by mhammond** [comment]
Some magic tends to be needed in https://dxr.mozilla.org/mozilla-central/source/browser/components/about/AboutRedirector.cpp - although I really can't recall how that is used and why, and whether that's strictly necessary (ie, Kit's outline may actually be all that's needed, but I've never experimented with that)

**Comment by mhammond** [comment]
Ficed in #19 - thanks Thom!
