### ISSUE TITLE
about:sync is reported as "Not compatible with multiprocess", by Add-on Compatibility Reporter

### ISSUE THREAD

**Issue by dholbert** [mhammond/aboutsync#20]
STR:
 1. In a fresh profile with Firefox Nightly, install the [about:sync](https://addons.mozilla.org/en-US/firefox/addon/about-sync/) and [Add-on Compatibility Reporter](https://addons.mozilla.org/en-US/firefox/addon/add-on-compatibility-reporter/) add-ons.
 2. Click the puzzle-piece in your Firefox toolbar (the compatibility-reporter icon)

ACTUAL RESULTS:
It says:
> About Sync extension for Firefox
> Version 0.0.5
> Not compatible with multiprocess.

EXPECTED RESULTS:
About Sync should be made compatible with multiprocess (e10s).

(Note: I don't know what is responsible for it being flagged as incompatible; I'm just noticing that it is, and reporting it.)

**Comment by mhammond** [comment]
Fixed in 04973b8
