### ISSUE TITLE
Plase update to remove Legacy badge

### ISSUE THREAD

**Issue by wellington1993** [mhammond/aboutsync#31]
Hi,

please update the addon! s2

Thanks...

**Comment by kitcambridge** [comment]
Hi! The "Legacy" badge just means it's not a Web Extension. Unfortunately, there are no Web Extension APIs for Sync, and I don't think we're planning to add any. For now, you'll need to use the add-on in Nightly. We'll need to figure out a long-term strategy.

**Comment by wellington1993** [comment]
@kitcambridge Nice. Thanks for the explanation. ;-)

**Comment by Gitoffthelawn** [comment]
Any update for use with WebExtensions API?

**Comment by mhammond** [comment]
This no longer has the "legacy" badge and works fine with recent Firefox versions.
