### ISSUE TITLE
about-sync noticed a sync failure

### ISSUE THREAD

**Issue by hovancik** [mhammond/aboutsync#32]
Hi, 
I am seeing this a lot last 2 days: 

![screen shot 2017-06-09 at 11 54 00](https://user-images.githubusercontent.com/4745859/26972752-589fbe78-4d13-11e7-81b4-b7cd054db879.png)

Not sure if it is safe to post the log here, but anyway, I opened tab on another device and I can see it on my main device. 

I'm on latest firefox on latest macOS, extesion 0.0.11

**Comment by mhammond** [comment]
This means you will find error logs in about:sync-logs - it would be great if you could file a bugzilla bug with the error logs - see https://wiki.mozilla.org/CloudServices/Sync/File_a_desktop_bug

**Comment by mhammond** [comment]
> in about:sync-logs

Sorry - about:sync-log
