### ISSUE TITLE
Change name to About Sync

### ISSUE THREAD

**Issue by grahamperrin** [mhammond/aboutsync#54]
… instead of _About Sync extension for Firefox_. 

![2018-05-14 23 32 33 waterfox](https://user-images.githubusercontent.com/192271/40026900-437b4fc2-57cf-11e8-9f3c-efd0839a0306.png)

- the word _extension_ is superfluous
- it also works with Waterfox (pictured). 

Thanks :-)

**Comment by mhammond** [comment]
Sorry for the delay here, but the name was changed back in August 2018, so I'm closing this.
