### ISSUE TITLE
Could not convert JavaScript argument arg 0

### ISSUE THREAD

**Issue by gemal** [mhammond/aboutsync#55]
`Error: [Exception... "Could not convert JavaScript argument arg 0 [nsISupports.QueryInterface]" nsresult: "0x80570009 (NS_ERROR_XPC_BAD_CONVERT_JS)" location: "JS frame :: chrome://aboutsync/content/build.js :: getSqlColumnNames :: line 27476" data: no]`

using version 0.0.2.1

**Comment by mhammond** [comment]
Version 0.0.22 was submitted to AMO on April 19 and is at only position 16 of 20 in the review queue :(

**Comment by grahamperrin** [comment]
Thanks, 0.0.22 is now available from AMO. Related: 

- [about:sync is blank with About Sync 0.0.22 with Waterfox 56.2.0 · Issue #56 …](https://github.com/mhammond/aboutsync/issues/56)

**Comment by gemal** [comment]
`Error: [Exception... "Could not convert JavaScript argument arg 0 [nsISupports.QueryInterface]" nsresult: "0x80570009 (NS_ERROR_XPC_BAD_CONVERT_JS)" location: "JS frame :: chrome://aboutsync/content/build.js :: getSqlColumnNames :: line 27595" data: no]`

same problem in 0.0.22 (new line number though)

**Comment by kitcambridge** [comment]
Hmm, I don't think this made it in to 0.0.22; that was cut in 26752a5a7ae09db7ff2b4aa0ec5b25aaef7d596c, which landed before 339bb7dcdaadfa43662398fb5fe53ce35df29430. But let's see if we can figure out what's going on with Waterfox, and sneak in a fix for that in 0.0.23, too...

**Comment by mhammond** [comment]
Sounds like this can be closed, but please reopen if there's still an issue.
