### ISSUE TITLE
Alerts: aboutsync:  not installing aboutsync extension into window of type alert:alert

### ISSUE THREAD

**Issue by wellington1993** [mhammond/aboutsync#59]
Hi, I'm have repeated messages related to:
Alerts: aboutsync:  not installing aboutsync extension into window of....
At my console and terminal.

Is possible to configure the add-on to hide this if necessary.

I'm using the console to debug some applications parts and it's useful hide this alerts if check marked or something like this.

Thanks...

**Comment by mhammond** [comment]
The next version will have them removed entirely (mainly because it will also have the item from the Tools menu removed entirely - typing "about:sync" into the address bar being the only way to open the addons seems reasonable to me)

**Comment by wellington1993** [comment]
@mhammond I'm think the same!
