### ISSUE TITLE
about:sync missing on Firefox nightly mobile

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [mhammond/aboutsync#76]
Extension installed and enabled but site is not found

![IMG_20210320_160013](https://user-images.githubusercontent.com/46166740/111874488-cd27c480-8995-11eb-8d51-1c19c36b54fd.jpg)

**Comment by mhammond** [comment]
This only works on Desktop Firefox. I thought I had specified that everywhere I could, so I'm not sure why it was even able to be installed on Android, but I'll have a look

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Ok. It's only currently installable in Firefox mobile nightly.

![IMG_20210321_010424](https://user-images.githubusercontent.com/46166740/111888971-aabb9880-89e1-11eb-940b-86dc84817f11.jpg)
![IMG_20210321_010444](https://user-images.githubusercontent.com/46166740/111888974-adb68900-89e1-11eb-8cc0-9ac89341f6ef.jpg)
![IMG_20210321_010512](https://user-images.githubusercontent.com/46166740/111888976-ae4f1f80-89e1-11eb-8087-1ef182bddf10.jpg)
