### ISSUE TITLE
about:sync is no longer recognized on nightly since 2022-04-06

### ISSUE THREAD

**Issue by lilydjwg** [mhammond/aboutsync#79]
Since [this change](https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=2a8c0b5c0596b49261acecd5f08df4174fe512a0&tochange=fafb7b2268f385506c5c650c819ac89f8a5b1648) `about:sync` is no longer recognized.

**Comment by mhammond** [comment]
Thanks - fixed by 759b770bc12acfe28f7acb12d8bc080aead47765 although I need to work out how to cut a release!
